### PR TITLE
Linting force comment

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Should it be forced? Am thinking of cases where `[ci skip]`/`[ci skip]` or `[lint skip]`/`[skip lint]` are used.

**Comment by isuruf** [comment]
This is for the case of command `please lint`

**Comment by jakirkham** [comment]
Right. However I wouldn't expect to run the linter if the commit messages explicitly disable it. Just as I wouldn't expect CI to be run on a PR where I have explicitly skipped them via commit messages.

**Comment by isuruf** [comment]
I was thinking of a case like, https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/69#issuecomment-333913863 where there is no feedback

**Comment by jakirkham** [comment]
It looks like it is just reusing the comment from before. That said, have no problem with adding an explicit comment from the linter when requested. Makes perfect sense to me.

Just would also expect the linter to respect the skip notes in commit messages as well. Perhaps it could say lint was skipped by commit message if we want a response for that case too.

**Comment by jakirkham** [comment]
...or is this already caught by the [`compute_lint_message`]( https://github.com/conda-forge/conda-forge-webservices/pull/137/files#diff-003f6ff938ed739a0d10990176da3f78R139 )?

**Comment by isuruf** [comment]
> ...or is this already caught by the compute_lint_message?

Yes, it is

**Comment by jakirkham** [comment]
LGTM. Good to merge?

**Comment by jakirkham** [comment]
Just realized we didn't have CI. Pushed to the repo to confirm it passes. Not expecting any surprises though. Feel free to merge when it passes.

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Pull request merged**
