### PR TITLE
Update to latest Miniforge (and use Conda)

### PR DESCRIPTION
**Pull request by jakirkham**
Updates to the latest Miniforge 24.3.0-0 in the Docker image used by Heroku to build and deploy the webservice.

Xrefs:
* https://github.com/conda-forge/conda-forge-webservices/pull/585
* https://github.com/conda-forge/miniforge/pull/574

Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

### CODE REVIEW

**Comment by jakirkham** [comment]
Marking as draft as we may want to jump to 24.3, which looks ready ( https://github.com/conda-forge/miniforge/pull/574 )

**Comment by jakirkham** [comment]
Updated to 24.3.0-0. Marking as ready for review

**Comment by beckermr** [comment]
Can you remind me why we think this won't crash the heroku server due to memory usage again?

I forget what changed in the latest conda.

**Comment by beckermr** [comment]
ahhhh nvm: https://github.com/conda-forge/conda-forge-webservices/pull/585#issuecomment-2014672064

**Comment by beckermr** [comment]
let's try it!

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Yep Conda 24.3.0 should have the memory fix we need 👍

Looks like it built successfully! 🎉

**Comment by jakirkham** [comment]
FWIW have run a few re-renders successfully. So think this is working well

**Pull request merged**
