### PR TITLE
Do update team before forking

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/conda-forge/conda-forge-webservices/issues/114

### CODE REVIEW

**Comment by jakirkham** [comment]
This seems to be changing `issue_comment`. Are we linting in issues somehow?

**Comment by isuruf** [comment]
Sorry, changed the title to do update team before forking

**Comment by jakirkham** [comment]
Thanks for the clarification. Thought there were even more neat features hiding somewhere. 😄

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Pull request merged**
