### PR TITLE
ENH move to docker

### LINKED ISSUE #199: Switch to using pytest
Currently we are using `nose`. Though it's not really maintained any more. We should switching to something that is. `pytest` is a nice option, which we already use for `conda-smithy`. So it's worth considering here.

### LINKED ISSUE #295: move to a docker container
This may help make the bot more responsive. See docs here: https://devcenter.heroku.com/articles/build-docker-images-heroku-yml

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

Closes #295 
Closes #199

### CODE REVIEW

**Comment by beckermr** [comment]
Alright @isuruf @jakirkham this one is ready for review. We will need to change the heroku build to container before we push this master.

**Comment by beckermr** [comment]
Also, ignore the circle error. This is related #303 and the fact that this one is not merged yet.

**Comment by isuruf** [comment]
Looks good to me. +1 to merge.

**Comment by beckermr** [comment]
Great! I’d like to merge the cron job pr first. That ok?

**Pull request merged**
