### PR TITLE
remove try import in preparation for mypy

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [x] CI is passing

### CODE REVIEW

**Comment by beckermr** [comment]
Why can't mypy handle try import patterns?

**Comment by wolfv** [comment]
It might, but do we still need this? This seems deprecated since Python 3.3 which is long EOL.

**Comment by wolfv** [comment]
Even `ruff` autocorrects this to the import from `unittest`.

**Comment by beckermr** [comment]
Oh sorry. Yes this pr is fine. I was wondering why this was mypy related.

**Pull request merged**
