### PR TITLE
Add command to update circle-ci deploy key

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, can you add a Circle-CI API token of a bot with admin access to the conda-forge heroku app as CIRCLE_TOKEN?

**Comment by jakirkham** [comment]
Do you know what bot’s CircleCI token is in `staged-recipes`?

**Comment by isuruf** [comment]
I think @pelson's token is in staged-recipes.

**Comment by isuruf** [comment]
Ping @jakirkham

**Comment by jakirkham** [comment]
I think we need to email Phil and ask him if he can do this for us. Would you be up for doing that? On a related note, I couldn't figure out how to give you admin permissions to CircleCI, but I know Phil has done that for me. Would encourage you to ask him about that too. Feel free to cc me if you would like.

**Comment by pelson** [comment]
Having a few issues with CircleCI availability today, so have struggled to get to the right place to set this up. I think all I need to do is to add the appropriate user in https://circleci.com/team/gh/conda-forge. I'll keep trying to do this today - hopefully the speed of the CircleCI interface will speedup at some point...

**Comment by pelson** [comment]
Actually, I think I've just done it. I authorized @conda-forge-admin on Circle and got an API key on the CircleCI interface. I've put that token in the CIRCLE_TOKEN environment variable on conda-forge-webservices. Could you double check if that is all that is needed @isuruf?

**Comment by isuruf** [comment]
Yes, that's it. Thanks. I think the only way to test this is to try it.

**Comment by pelson** [comment]
Go for it.

Out of interest, where has the git requirement come from? Isn't the dependency on gitpython sufficient?

**Comment by isuruf** [comment]
`gitpython` doesn't work with the latest git installed in heroku. So, I'm installing the old version that is in conda-forge. (we should update both `gitpython` and `git` to the latest release in `conda-forge` btw

**Comment by pelson** [comment]
Thanks.
Do you have access to the Heroku account btw? I can add you there now if you give me your username (and you want to be added)

**Comment by isuruf** [comment]
I already do have access to the heroku account. @jakirkham gave me access a while ago. I just didn't have access to the bots.

**Comment by jakirkham** [comment]
Thanks @pelson and @isuruf!

**Pull request merged**
