### PR TITLE
Update `anaconda-client` too

### PR DESCRIPTION
**Pull request by jakirkham**
Include `anaconda-client` in the packages to update on redeployment.

<hr>

Checklist
* [x] Pushed the branch to main repo
* [ ] CI passed on the branch

### CODE REVIEW

**Comment by jakirkham** [comment]
pre-commit.ci autofix

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Should the bot add this to this file itself? Or do we need to do something on our end?

https://github.com/conda-forge/conda-forge-webservices/blob/640130affd89eed76885f4ead7ea5191fbb670bd/pkg_versions.json#L1

**Comment by jakirkham** [comment]
FWIW [the recent `clean-and-update` run]( https://github.com/conda-forge/conda-forge-webservices/actions/runs/8524087271 ) didn't update `anaconda-client`. Are we missing something else?

**Comment by beckermr** [comment]
That will get updated on the next release of a package that forces a webservices redeploy.

**Comment by jakirkham** [comment]
Right. Just thought it would add `anaconda-client` to that file as it did with others here ( https://github.com/conda-forge/conda-forge-webservices/commit/8ccbbe9d2beaa6fabeda23a4b2a5b6f72f9e34d9 ), but that doesn't appear to be the case

**Comment by beckermr** [comment]
yep when a new package version is shipped, it will get added.

**Comment by jakirkham** [comment]
Ok going to manually add it then so we have a record of the current version: https://github.com/conda-forge/conda-forge-webservices/pull/603

**Pull request merged**
