### PR TITLE
PERF background slow tasks

### LINKED ISSUE #25: Background the linting process
As per the suggestion at https://devcenter.heroku.com/articles/background-jobs-queueing we probably shouldn't be blocking the webservice for the few seconds that it takes to run the linting.

### PR DESCRIPTION
**Pull request by beckermr**
Closes #25 

Checklist
* [x] Pushed the branch to main repo
* [ ] CI passed on the branch

### CODE REVIEW

**Comment by jakirkham** [comment]
Do we need to await these somewhere or is that already done for us?

**Comment by beckermr** [comment]
They are awaited right in the function with the await keywords

**Comment by jakirkham** [comment]
SGTM. Merge when ready 🙂

**Comment by beckermr** [comment]
See this one: http://www.tornadoweb.org/en/stable/faq.html#why-isn-t-this-example-with-time-sleep-running-in-parallel

**Comment by beckermr** [comment]
See item 3

**Pull request merged**
