### PR TITLE
ENH added command to add the bot-rerun label

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds a web services command to add the bot-rerun label to PRs.

Checklist
* [ ] Pushed the branch to main repo
* [ ] CI passed on the branch

@conda-forge/core @CJ-Wright for viz

### CODE REVIEW

**Comment by beckermr** [comment]
This PR needs the color and description.

""color": "#191970""
"'description': 'Apply this label if you want the bot to retry issueing a particular pull-request'"

**Comment by CJ-Wright** [comment]
Would you be able to put up PRs into the CF docs and the bot's PR template letting people know that this exists?

**Comment by beckermr** [comment]
I think I need to make sure the label exists before making the API call to add it.

**Comment by beckermr** [comment]
@CJ-Wright I wonder which migrators should have the message? Version and YAML? A lot of the migrators hav custom PR bodies and so to some extent it is up to the people who submit them to decide if they want this mentioned.

**Comment by beckermr** [comment]
Ahhhh NM. I'll put in the base class. Most of the migrators format that properly except for Aarch.

**Comment by beckermr** [comment]
OK @CJ-Wright @conda-forge/core this PR is ready for another look.

**Comment by CJ-Wright** [comment]
I'm not certain why travis is unhappy, but it is.

**Comment by beckermr** [comment]
This repo requires someone with write access to bring the branch from my fork into the main repo and then reun the tests. The tests require a github api key that is not allowed on forks. 

@scopatz @jakirkham @isuruf have done this for me in the past

**Comment by beckermr** [comment]
bump here @conda-forge/core

**Comment by jakirkham** [comment]
Would it be possible to get a test for this?

**Comment by beckermr** [comment]
Sure

**Comment by beckermr** [comment]
@jakirkham I have added a test of the command! Back to you!

**Comment by beckermr** [comment]
BTW, the test passes locally but the CI here will fail because it needs to be run on a branch in the main repo, not my fork.

**Comment by beckermr** [comment]
bump again here @jakirkham @conda-forge/core !

**Comment by scopatz** [comment]
Thanks yeah - tests are expected to fail here.  Can you also add a note on this to the docs, please @beckermr? Thanks!

**Comment by jakirkham** [comment]
He already did. I merged it a few days back.

**Comment by isuruf** [comment]
> Thanks yeah - tests are expected to fail here. 

@scopatz, I'm sorry, but I've mentioned this to you 4 times already that somebody from core has to push the branch to a different branch in this repo to run the tests. Please don't ignore this. I've added a checklist to the top, but this is ignored by you many times.

**Comment by isuruf** [comment]
I've enabled status checks so that pushing to a branch is required before merging. Let me know if that's too restrictive.

**Pull request merged**
