### PR TITLE
ENH fix linting double comments

### PR DESCRIPTION
**Pull request by beckermr**
related to #349

Checklist
* [x] Pushed the branch to main repo
* [ ] CI passed on the branch

### CODE REVIEW

**Comment by beckermr** [comment]
cc @jakirkham

**Comment by jakirkham** [comment]
Thanks Matt! 😀

**Comment by isuruf** [comment]
@beckermr, should this be reverted as this is not the issue?

**Comment by beckermr** [comment]
I took this code out in another pr already.

**Pull request merged**
