### PR TITLE
REF less api calls for stale

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

### CODE REVIEW

**Comment by beckermr** [comment]
OK @isuruf @conda-forge/staged-recipes @conda-forge/core this is ready for review!

**Comment by beckermr** [comment]
I already turned it on. Working great! This was a refactor.

**Comment by CJ-Wright** [comment]
Oh, the stale bot is running?

**Comment by beckermr** [comment]
yup it should be!

**Comment by beckermr** [comment]
it issues one thing an hour right now

**Comment by jakirkham** [comment]
Cool, thanks for working on this! 😄

**Pull request merged**
