### PR TITLE
make bot commands more flexible / search more precise

### PR DESCRIPTION
**Pull request by dougalsutherland**
I never remember whether the command is "please rerender" or "please re-render"; this change makes both work. It also makes "please add `noarch: python`", "please make noarch python", etc valid too in addition to just "please add noarch: python".

While I was making that change, I realized that the current check was a little unintuitive. For example, if I tagged conda-forge-admin here, then it would actually add noarch (if this were a feedstock) because I said the command above (completely separated from the tag). That's not incredibly likely to happen, but still, this change stops that: you now have to tag the bot, optionally add a comma/colon/whitespace, then immediately say the command.

(I didn't add tests for these, since there weren't any for the commands in the first place.)

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems fine in principle. Any thoughts on tests for these changes?

**Comment by dougalsutherland** [comment]
I can try adding some tests with comments that should / shouldn't trigger commands, with the actual edits mocked out, later on.

**Comment by jakirkham** [comment]
Sure. Yeah even a check to see that it would trigger the bot would be good.

Depending on what you have in mind, [these tests]( https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/tests/linting/test_compute_lint_message.py ) might be useful to steal from.

**Comment by dougalsutherland** [comment]
Added some tests, and in doing so caught some minor bugs in the current logic. :)

**Comment by dougalsutherland** [comment]
This is a little beyond the scope of the initial PR now, but I also went ahead and added support for opening a `please rerender` issue, for the occasional situation where the only thing wrong is that the rendering needs to be updated.

**Comment by jakirkham** [comment]
Thanks for looking into these things. Sounds like you are fixing some issues that we have been slow to address thus far, but are aware of. References below.

> This is a little beyond the scope of the initial PR now, but I also went ahead and added support for opening a `please rerender` issue, for the occasional situation where the only thing wrong is that the rendering needs to be updated.

Sounds like issue ( https://github.com/conda-forge/conda-forge-webservices/issues/112 ).

> Both that and `add noarch python` should probably bump the version number, though....

Sounds like issue ( https://github.com/conda-forge/conda-forge-webservices/issues/125 ).

**Comment by jakirkham** [comment]
Could you also push these changes to this repo under the branch name `dougalsutherland/command-flexibility`? Most of the tests require a test token, which is not provided in fork CI builds (understandably).

**Comment by dougalsutherland** [comment]
@conda-forge/conda-forge-webservices, this is ready for review. :)

**Comment by isuruf** [comment]
Thanks @dougalsutherland

**Comment by jakirkham** [comment]
FWIW IMHO we should add the re-rendering commands to issues as there are enough scenarios where I or other did not have a PR, but needed a re-render. Would be helpful in these scenarios to just allow the command and have the bot do the work.

**Comment by isuruf** [comment]
+1

**Comment by dougalsutherland** [comment]
Yeah, it just makes more sense to have it bump the build number too, which requires actually parsing the meta.yaml at least somewhat, so I put it off....

**Comment by isuruf** [comment]
Even without bumping the build number, it'll be useful to fix incorrect renderings by users.

**Comment by jakirkham** [comment]
Agreed. If someone wants to put a PR for this, would be +1 on merging.

**Pull request merged**
