### PR TITLE
ENH adding automerge

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Pushed the branch to main repo
* [ ] CI passed on the branch

Closes #290

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/core this one is ready for review!

**Comment by scopatz** [comment]
Thanks!

**Comment by CJ-Wright** [comment]
How soon until this goes into production? (do we need to restart the web service?)

**Comment by jakirkham** [comment]
After CI passes it will redeploy.

**Comment by beckermr** [comment]
@jakirkham did we break the bot? I am not seeing rerender PRs in issues...

**Comment by beckermr** [comment]
nm we see it

**Comment by jakirkham** [comment]
Yeah it deployed 🙂

**Comment by beckermr** [comment]
Can you tell us what version of conda-smithy it installed?

**Comment by jakirkham** [comment]
Looks like `3.6.6`. Here's everything that is installed:


<details>

```
/app/.conda/bin/conda list --show-channel-urls
# packages in environment at /app/.conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
asn1crypto                0.24.0                   py37_0    defaults
beautifulsoup4            4.8.2                    py37_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.12.2           py37h2e261b9_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                        py_0    conda-forge
conda                     4.6.14                   py37_0    conda-forge
conda-build               3.18.11                  py37_0    conda-forge
conda-forge-pinning       2020.01.24                    0    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
conda-smithy              3.6.6                      py_0    conda-forge
cryptography              2.6.1            py37h1ba5d50_0    defaults
curl                      7.65.3               hf8cf82a_0    conda-forge
deprecated                1.2.7                      py_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
filelock                  3.0.10                     py_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
git                       2.24.0          pl526hce37bd2_1    conda-forge
gitdb2                    2.0.6                      py_0    conda-forge
gitpython                 3.0.5                      py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      py37_0    defaults
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libiconv                  1.15              h516909a_1005    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markdown2                 2.3.6                      py_0    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
msrest                    0.6.10                     py_0    conda-forge
ncurses                   6.1                  he6710b0_1    defaults
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.0.3                   py37_0    defaults
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1           py37h516909a_1003    conda-forge
pygithub                  1.43.6                   py37_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.6                h357f687_2    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.21.0                   py37_0    defaults
requests-oauthlib         1.2.0                      py_0    conda-forge
ripgrep                   11.0.2               h516909a_3    conda-forge
ruamel.yaml               0.16.6           py37h516909a_0    conda-forge
ruamel.yaml.clib          0.2.0            py37h516909a_0    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                41.0.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
smmap2                    2.0.5                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statuspage                0.8.1                      py_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.41.1                     py_0    conda-forge
urllib3                   1.24.1                   py37_0    defaults
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.33.1                   py37_0    defaults
wrapt                     1.11.2           py37h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

</details>

**Comment by beckermr** [comment]
Nice! So our PR is just buggy. :/

I'll push a fix later

**Comment by jakirkham** [comment]
In what way is it buggy?

**Comment by beckermr** [comment]
the command doesn't work!

**Pull request merged**
