### PR TITLE
BUG make sure to use the latest conda-smithy

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

### CODE REVIEW

**Comment by beckermr** [comment]
We went ahead an removed the 4.6 pinning here @isuruf. That ok?

**Comment by beckermr** [comment]
@jakirkham any thoughts on the conda version here? It was pinned at 4.6

**Comment by beckermr** [comment]
Ok merging. Hopefully nothing breaks.

**Comment by jakirkham** [comment]
Sorry for missing this. IDK that anyone knows why that was pinned any more. Presumably 4.7 broke something in the webservice at some point. That said, I agree it seems reasonable to try a new version and see how it goes. In the worst case we can always rollback 🙂

**Pull request merged**
