### PR TITLE
this seemed like a typo

### PR DESCRIPTION
**Pull request by CJ-Wright**
Maybe this fixes things?

Checklist
* [ ] Pushed the branch to main repo
* [ ] CI passed on the branch

### CODE REVIEW

**Comment by isuruf** [comment]
This check doesn't work with the CDN as there's a delay between CI finishing and package being available.

**Comment by CJ-Wright** [comment]
I'm confused, I'm trying to fix #274

**Comment by isuruf** [comment]
What I'm saying is it doesn't matter whether you fix #274 or not.

**Comment by CJ-Wright** [comment]
Ah ok

**Pull request closed without merging**
