### PR TITLE
Update conda-build to latest in webservice

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM Thanks @isuruf! Just waiting on CI

**Comment by scopatz** [comment]
Hmm I don't know why the PR build was canceled

**Comment by isuruf** [comment]
PR builds fail in this repo. Tests need a github token. So I pushed to `isuruf/cb` branch in this repo.

**Comment by scopatz** [comment]
Ahh OK

**Pull request merged**
