### PR TITLE
Don't lint on all action types

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

### CODE REVIEW

**Comment by isuruf** [comment]
How about removing line 158 ?

**Comment by beckermr** [comment]
What is in that line?

**Comment by isuruf** [comment]
`lint_info = await tornado.ioloop.IOLoop.current().run_in_executor(`

**Comment by beckermr** [comment]
Ahhhh. This is going to really slow the server down, so I'd prefer not.

**Comment by isuruf** [comment]
Let's fix conda_smithy then. This PR should go in regardless because we don't need to lint for other action types.

**Comment by beckermr** [comment]
We need to lint on push right?

**Comment by isuruf** [comment]
These are the action types,
`assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked`

Pushing a commit is `synchronize`.

**Comment by beckermr** [comment]
Ok. LGTM!

**Pull request merged**
