### PR TITLE
ENH added command to restart CI services

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Pushed the branch to main repo
* [ ] CI passed on the branch

addresses part of #107 

@jakirkham for viz

### CODE REVIEW

**Comment by beckermr** [comment]
hey @conda-forge/core! I've added a command to the admin bot that restarts CI services via closing and then opening PRs. This method is pretty crude, but works well and is simple to maintain. The command looks like one of

```
@conda-forge-admin, please restart build
@conda-forge-admin, please restart builds
@conda-forge-admin, please restart ci
```

with the `please` being optional.

It will work on any feedstock and I enabled it for staged recipes as well.

**Comment by scopatz** [comment]
Thanks!

**Comment by isuruf** [comment]
@scopatz, please don't merge PRs to this repo without the two checklists above have been completed.

**Comment by beckermr** [comment]
woops. :/ Hopefully it just works?

**Comment by isuruf** [comment]
Nope. Master fails, https://travis-ci.org/conda-forge/conda-forge-webservices/builds/580870030

**Comment by beckermr** [comment]
Looks like the test failure is not related to this PR

```
======================================================================
FAIL: test_good_recipe (conda_forge_webservices.tests.linting.test_compute_lint_message.Test_compute_lint_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/conda-forge/conda-forge-webservices/conda_forge_webservices/tests/linting/test_compute_lint_message.py", line 48, in test_good_recipe
    self.assertMultiLineEqual(expected_message, lint['message'])
AssertionError: '\nHi[208 chars].\n\n' != '\nHi[208 chars].\n\n\nI do have some suggestions for making i[104 chars]d.\n'
  
  Hi! This is the friendly automated conda-forge-linting service.
  
  I just wanted to let you know that I linted all conda-recipes in your PR (```recipes/good_recipe```) and found it was in an excellent condition.
  
+ 
+ I do have some suggestions for making it better though...
+ 
+ 
+ For **recipes/good_recipe**:
+ 
+  * license_file entry is missing, but is expected.
```

**Comment by beckermr** [comment]
I also did not write a test. :(

My bad. 

Happy to write one once the commits here are backed out.

**Comment by isuruf** [comment]
Ah, that failure is not related. Can you send a PR with a new test? (And also fix the existing failing test if you have the time?)

**Comment by isuruf** [comment]
Nvm, I fixed the good_recipe at https://github.com/conda-forge/conda-forge-webservices/pull/16

**Comment by beckermr** [comment]
Happily! IDK how to run the tests outside of the CI on master with a GH token. I'll write the test and then ping you.

**Comment by isuruf** [comment]
Only tests in `tests/test_webapp.py` need a github token. `tests/test_commands.py` doesn't which is where a test for this PR's new functionality has to be written.

**Comment by beckermr** [comment]
tests are great - but it works!

https://github.com/conda-forge/instaseis-feedstock/pull/17

**Comment by isuruf** [comment]
Also a documentation PR to update https://github.com/conda-forge/conda-forge.github.io/blob/master/src/maintainer/infrastructure.rst#admin-web-services would be great.

**Comment by beckermr** [comment]
Also works on a branch I don't own in a PR I don't maintain. https://github.com/conda-forge/instaseis-feedstock/pull/16

**Comment by beckermr** [comment]
I am busy at a workshop the next two days. I probably won't get to this until next week. Thanks for your patience!

**Comment by isuruf** [comment]
No problem. Let me know if you need help.

**Comment by jakirkham** [comment]
Raised in issue ( https://github.com/conda-forge/conda-forge-webservices/issues/268 ).

**Pull request merged**
