### PR TITLE
ENH try to make the package before the copy to get attrs

### PR DESCRIPTION
**Pull request by beckermr**
This PR tries to make the package on the production server before we copy it. This should allow us to properly set the package attributes.

Checklist
* [x] Pushed the branch to main repo
* [x] CI passed on the branch

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for working on this Matt! 😄

Do you recall what is still incomplete here (thinking about the draft status)? 🙂

**Comment by beckermr** [comment]
This won't fix the issue. The copy removes the info on anaconda.org anyways. :/

**Comment by jakirkham** [comment]
Oh interesting. What if we add the info after the copy? Or are there issues with that approach as well?

**Comment by beckermr** [comment]
We cannot adjust the info on anaconda.org after we create the package. We will have to be able to do this to fix the packages we already have.

**Comment by beckermr** [comment]
Closing as this has been fixed upstream.

**Pull request closed without merging**
