### PR TITLE
OLD: TESTING BRANCH: Added an ok recipe.

### PR DESCRIPTION
**Pull request by jakirkham**
Please unsubscribe from this PR - it is a testing branch and will be noisy.

This adds a second good recipe called `ok_recipe` as a PR to the `good_recipe` branch. Thus it should be useful for testing cases where recipes in the base branch should be excluded or not.

### CODE REVIEW

**Comment by pelson** [comment]
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```ok_recipe```) and found some lint.

Here's what I've got...


For **ok_recipe**:

 * The recipe must have a `build/number` section.

**Comment by pelson** [comment]
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```ok_recipe```) and found it was in an excellent condition.

**Comment by jakirkham** [comment]
Replaced by PR ( https://github.com/conda-forge/conda-forge-webservices/pull/54 ).

**Comment by jakirkham** [comment]
Please don't delete this branch or repo this PR. It is for testing only.

**Comment by jakirkham** [comment]
Please don't delete this branch or reopen this PR. It is for testing only.

**Comment by jakirkham** [comment]
Please don't delete this branch or reopen this PR. It is for testing only.

**Pull request closed without merging**
