### PR TITLE
feat: change command recipe path

### PR DESCRIPTION
**Pull request by tdejager**
This supersedes #644 and #643.

Only modifies the recipe path, so that the commands are also applied to rattler-build recipe.yaml.

cc @isuruf @beckermr 

Checklist
* [x] CI is passing

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Please make this PR without all of the unassociated style changes to the single vs double quotes. Maybe black was applied? I cannot read these diffs and figure out what is a style versus a functional changed.

I am ok with black or ruff-format or w/e here, but we need to have one thing per PR.

**Comment by tdejager** [comment]
Yeah sorry, somehow vscode was applying these automatically, will revert those changes tomorrow.

**Comment by tdejager** [comment]
Changed it to just contain the changes. Two notes/questions.

I'm returning None from the `add_user` as that is checked, and False from the `make_noarch`. Don't know if you guys agree with that, we can also throw an Exception, ignore, or add a `None` check to `make_noarch` places.

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
Ideally the admin would make a comment that the recipe was missing. We can do that later if we want.

**Pull request merged**
