### PR TITLE
Suggest updating feedstock-outputs if outputs are invalid

### PR DESCRIPTION
**Pull request by eriknw**
I don't have permission to push to a branch on this repo.

Checklist
* [ ] Pushed the branch to main repo
* [ ] CI passed on the branch

### CODE REVIEW

**Comment by beckermr** [comment]
I'll do it in a bit. (In a car) Thanks for the pr!

**Comment by jakirkham** [comment]
Thanks Erik! 🙏

Went ahead and pushed to [`eriknw/invalid_outputs_suggestion`]( https://github.com/conda-forge/conda-forge-webservices/tree/eriknw/invalid_outputs_suggestion )

**Comment by jakirkham** [comment]
Is there a good way to test this? Do we have a feedstock that we can use for that kind of thing?

**Comment by beckermr** [comment]
We should merge. I don't think we have a test that works and making one is going to be hard.

**Pull request merged**
