### PR TITLE
Run new conda_forge lints

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jakirkham** [comment]
Pushed this to the repo for you so that it can be tested (requires a GitHub token for some of the tests).

**Comment by isuruf** [comment]
I'm sorry, how do I test it?

**Comment by jakirkham** [comment]
By pushing the branch to this repo directly. Have just added you to `conda-forge/conda-forge-webservices` so that you can do this as needed.

**Comment by jakirkham** [comment]
Should add that I pushed these changes to the branch `isuruf/lint` on this repo.

**Comment by isuruf** [comment]
And if I add a recipe to the root, it would automatically check the recipe?

**Comment by jakirkham** [comment]
It searches for anything that looks like a recipe (has a `meta.yaml`). We put these in PRs like [this one]( https://github.com/conda-forge/conda-forge-webservices/pull/62 ). Though it might be worth building off of existing PRs to cutdown on the number of these we create (if possible). There are checks for [the message]( https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/tests/linting/test_compute_lint_message.py ) that one gets, which are the most useful. Though we also have [integration tests]( https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/tests/linting/test_main.py ) that comment on the PR if needed.

**Comment by isuruf** [comment]
@jakirkham, can you explain what I have to do? Btw, these lints are checked in conda-smithy.

**Comment by jakirkham** [comment]
So if you have already changed the bad recipe, would update the message in the [bad recipe test]( https://github.com/conda-forge/conda-forge-webservices/blob/e5ddf678f7e3b579cecd327d1a1b26fc7eac95da/conda_forge_webservices/tests/linting/test_compute_lint_message.py#L122 ).

Were there any things that we weren't testing in `conda-smithy` that would require a token? If so, this is something we should try testing here.

**Comment by isuruf** [comment]
Changed `bad_recipe` again to check one more lint that needed `GH_TOKEN`. I'll update the test

**Comment by isuruf** [comment]
Tests pass. Merging.

**Comment by isuruf** [comment]
Does this get deployed immediately?

**Comment by jakirkham** [comment]
It is suppose to build and deploy on Heroku after you merge. Though I don't think it has.

**Comment by jakirkham** [comment]
Should now be deployed.

**Pull request merged**
