### PR TITLE
Don't require "please" in any of the @conda-forge-admin commands

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
I guess it's impossible for me to run the tests. I suppose someone should push this branch up to this repo to see if they work.

**Comment by scopatz** [comment]
Thanks @asmeurer! Not sure why all the tests are failing here... @conda-forge/core

**Comment by asmeurer** [comment]
The tests failed locally too. I guess the way they are written they can't pass unless GH_TOKEN is set. That would be the case for branches pushed to this repo (https://github.com/conda-forge/conda-forge-webservices/blob/48134fc7ba0b6946556d543cbcc027f2c4bbffef/.travis.yml#L13), but not for pull requests from forks.

**Comment by scopatz** [comment]
OK I can make a PR from this repo

**Comment by asmeurer** [comment]
I think it you just push the branch it will show the build here (no new PR needed). And obviously if I need to push new commits you will need to push them as well.

**Comment by scopatz** [comment]
OK I just pushed the branch

**Comment by scopatz** [comment]
I think it does need a new PR

**Comment by jakirkham** [comment]
Tests require a token, which is set as a secure environment variable. This is not available in PRs, but is available for branches on this repo.

**Comment by asmeurer** [comment]
The push build is showing up here (it passed). It still will have the failed PR build, though, so if that prevents merging you will need a new PR.

**Comment by jakirkham** [comment]
We just ignore the failed PR build. It's understood to be meaningless.

**Comment by jakirkham** [comment]
@conda-forge/core, thoughts on this change?

**Comment by CJ-Wright** [comment]
this seems fine to me

**Pull request merged**
